on:
  schedule:
    - cron: "0 0 * * *" # This should run every hour
  workflow_dispatch:

name: Docker images

jobs:
  build-images:
    name: Build & push Docker images
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        runtime:

          - name: freedesktop-21.08
            packages: org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
            remote: flathub

          - name: freedesktop-22.08
            packages: org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
            remote: flathub

          - name: gnome-40
            packages: org.gnome.Platform//40 org.gnome.Sdk//40
            remote: flathub

          - name: gnome-41
            packages: org.gnome.Platform//41 org.gnome.Sdk//41
            remote: flathub

          - name: gnome-42
            packages: org.gnome.Platform//42 org.gnome.Sdk//42
            remote: flathub

          - name: gnome-43
            packages: org.gnome.Platform//43 org.gnome.Sdk//43
            remote: flathub

          - name: kde-5.15
            packages: org.kde.Platform//5.15 org.kde.Sdk//5.15 io.qt.qtwebengine.BaseApp//5.15
            remote: flathub

          - name: kde-5.15-21.08
            packages: org.kde.Platform//5.15-21.08 org.kde.Sdk//5.15-21.08 io.qt.qtwebengine.BaseApp//5.15-21.08
            remote: flathub

          - name: kde-5.15-22.08
            packages: org.kde.Platform//5.15-22.08 org.kde.Sdk//5.15-22.08 io.qt.qtwebengine.BaseApp//5.15-22.08
            remote: flathub

    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          driver-opts: network=host

      - name: Cache Docker layers for the base image
        uses: actions/cache@v3.2.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build & push the Fedora base image to local registry
        uses: docker/build-push-action@v3.2.0
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: Dockerfile
          pull: true
          push: true
          tags: localhost:5000/fedora-base:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          cat >> ${{ matrix.runtime.name }}.Dockerfile << EOF
          # syntax = docker/dockerfile:experimental
          FROM localhost:5000/fedora-base:latest
          RUN --security=insecure flatpak install -y --noninteractive ${{matrix.runtime.remote}} ${{ matrix.runtime.packages }}
      - name: Build & push the ${{ matrix.runtime.name }} image to Docker Hub
        uses: docker/build-push-action@v3.2.0
        with:
          allow: security.insecure
          context: .
          file: ${{ matrix.runtime.name }}.Dockerfile
          push: true
          tags: asganarei/flatpak_asga:${{ matrix.runtime.name }}
